import Head from "next/head";
import Image from "next/image";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <motion.div
      initial={{ y: "100%" }}
      animate={{ y: "0%" }}
      transition={{ duration: 0.75, ease: "easeInOut" }}
      exit={{ opacity: 1 }}
      className="text-gray-900 absolute top-0 left-0 w-full bg-orange-200 lg:px-48 px-16"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="my-96 p-1">
          <h1 className="text-6xl text-center lg:text-right lg:text-9xl">
            Happy Pickle
          </h1>
        </div>
        <div className="flex justify-between">
          <div className="">
            <h2 className="">Design</h2>
            <h2 className="">Company</h2>
            <h2 className="">2022</h2>
          </div>
          <div className="">
            <h3>This pickle gonna make you smile.</h3>
            <h3>Scottish designs to make you happy.</h3>
            <h3>Click contact for cool transition.</h3>
          </div>
        </div>
      </main>
    </motion.div>
  );
}
