import Head from "next/head";
import Image from "next/image";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="my-60 p-1">
          <h1 className="text-6xl text-center lg:text-right lg:text-9xl">
            Happy Pickle
          </h1>
        </div>
        <div className="flex justify-between">
          <div className="">
            <h2 className="">Design</h2>
            <h2 className="">Company</h2>
            <h2 className="">2022</h2>
          </div>
          <div className="">
            <h3>This pickle gonna make you smile.</h3>
            <h3>Scottish designs to make you happy.</h3>
            <h3>Click contact for cool transition.</h3>
          </div>
        </div>
      </main>
    </div>
  );
}
